version: "3.8"

services:
  ui:
    build:
      context: ElGen_UI
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./ElGen_UI/src:/code/src
      - /project/node_modules
    expose:
      - 3306
      - 33060

  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
      - sonarqube
    build: ./ElGen
    restart: on-failure
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username": "$MYSQLDB_USER",
        "spring.datasource.password": "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL57Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  sonarqube:
    image: sonarqube:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonarscanner_backend:
    image: maven:3.8.1-openjdk-17
    depends_on:
      - sonarqube
    volumes:
      - ./ElGen:/usr/src/backend
      - .m2:/root/.m2
    working_dir: /usr/src/backend
    command: >
      mvn clean verify sonar:sonar
      -Dsonar.projectKey=backend
      -Dsonar.host.url=http://sonarqube:9000
      -Dsonar.login=admin
      -Dsonar.password=admin123

  sonarscanner_frontend:
    image: sonarsource/sonar-scanner-cli:latest
    depends_on:
      - sonarqube
    volumes:
      - ./ElGen_UI:/usr/src/frontend
    working_dir: /usr/src/frontend
    command: >
      sonar-scanner
      -Dsonar.projectKey=frontend
      -Dsonar.sources=src
      -Dsonar.host.url=http://sonarqube:9000
      -Dsonar.login=admin
      -Dsonar.password=admin123

volumes:
  db:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
